sudo: required

dist: xenial

services:
  - docker

before_install:
  - docker -v
  # Use the env config
  # - cp .env.example .env
  # Stop the postgres instance travis sets up automatically
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop

  # Create a loop
  - sudo ifconfig
  # - sudo ifconfig lo:0 10.254.254.254 netmask 255.0.0.0 up
install:
  # Start the docker stuff
  - docker-compose build
  - docker-compose up -d
  - sleep 10
  # Install dev php dependencies
  # - docker-compose exec web sh -c "composer install --no-interaction --prefer-dist"
script:
  # Seed database
  - docker-compose exec php_backend sh -c "php vendor/bin/phinx migrate"
  - docker-compose exec php_backend sh -c "php vendor/bin/phinx seed:run"
  - curl http://local.app.basereality.com
  - docker-compose exec php_backend sh -c "php vendor/bin/behat --config=./behat.yml --colors --stop-on-failure"
  # Run tests
  # - docker-compose exec web sh -c "composer test"

notifications:
  email: false