sudo: required

dist: xenial

services:
  - docker

before_install:
  - docker -v
  # Stop the postgres instance travis sets up automatically
  - sudo /etc/init.d/postgresql stop
  - sudo service mysql stop
  # Create a loopback address
  - sudo ip addr add 10.254.254.254/32 dev lo

install:
  # Start the docker stuff
  - docker-compose build
  - docker-compose up -d
  - sleep 10
  # Install dev php dependencies
  # - docker-compose exec web sh -c "composer install --no-interaction --prefer-dist"
script:
  - docker-compose exec php_fpm sh -c "php vendor/bin/phpcs --standard=./test/codesniffer.xml --encoding=utf-8 --extensions=php -p -s lib"
  - docker-compose exec php_fpm sh -c "php phpstan.phar analyze -c ./phpstan.neon -l 7 lib"
  - docker-compose exec php_fpm sh -c "php vendor/bin/phinx migrate"
  - docker-compose exec php_fpm sh -c "php vendor/bin/phinx seed:run"
  # Make sure site is working at least a bit.
  - curl http://local.app.basereality.com
  - docker-compose exec php_fpm sh -c "php vendor/bin/behat --config=./behat.yml --colors --stop-on-failure"

notifications:
  email: false