version: "3"
services:
  chrome:
    ## This image may be more stable, but doesn't give any output when Chrome
    ## headless crashes
    # image: justinribeiro/chrome-headless:latest
    ## This image is more up-to-date....but can be too bleeding edge, aka more
    ## likely to see bugs.
    image: alpeware/chrome-headless-trunk
    ports:
      - "9222:9222"
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
  selenium-chrome:
    image: selenium/standalone-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
      - "5900:5900"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    environment:
      VNC_NO_PASSWORD: 1
      SCREEN_WIDTH: 1200
      SCREEN_HEIGHT: 900
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: LuwCDE97zppvQhzP
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: D9cACV8Pue3CvM93
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/config/my.cnf:/etc/mysql/my.cnf
      - ./data/mysql:/var/lib/mysql
      - ./data/mysql_import:/docker-entrypoint-initdb.d
  php_fpm:
    build: docker/php_fpm
    image: example_php_fpm
    depends_on:
      - db
      - redis
    volumes:
      - .:/var/www
  php_fpm_debug:
    build: docker/php_fpm_debug
    depends_on:
      - db
      - redis
      - php_fpm
    volumes:
      - .:/var/www
  redis:
    image: redis:4.0.6
    ports:
      - "6379:6379"
    volumes:
      - .:/var/www
    command: ["redis-server", "/var/www/docker/redis/config/redis.conf"]
#  varnish:
#    build: docker/varnish

#    command: ["/usr/local/bin/start_varnish.sh"]
#    depends_on:
#      - web_server
#    environment:
#      CACHE_SIZE: 128m
#    ports:
#      - "80:80"
#    volumes:
#      - ./config/localdev/varnish:/etc/varnish
#      - ./:/var/app
  nginx:
    build: docker/nginx
    depends_on:
      - db
      - redis
      - php_fpm
      - php_fpm_debug
    volumes:
      - .:/var/www
    ports:
      - "80:80"
      - "8000:8000"
      - "8001:8001"
  supervisord:
    build: docker/supervisord
    depends_on:
      - redis
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www

# https://rskuipers.com/entry/file-permissions-with-docker-on-linux
# fpm:
    # For Linux users only (UID of your user)
 #   user: "1000"