version: "3"
services:

  selenium-chrome:
    image: selenium/standalone-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
      - "5900:5900"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    #  - 192.168.9.45
    environment:
      VNC_NO_PASSWORD: 1
      SCREEN_WIDTH: 1080
      SCREEN_HEIGHT: 1080
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: LuwCDE97zppvQhzP
      MYSQL_DATABASE: example
      MYSQL_USER: example
      MYSQL_PASSWORD: D9cACV8Pue3CvM93
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/config/my.cnf:/etc/mysql/my.cnf
      - ./data/mysql:/var/lib/mysql
      - ./data/mysql_import:/docker-entrypoint-initdb.d
  php_backend:
    build: docker/php_backend
    image: example_php_backend:latest
    depends_on:
      - db
      - redis
    volumes:
      - .:/var/www
      # - ./logs/php_backend:/var/log/api
  php_backend_debug:
    build: docker/php_backend_debug
#    image: example_php_backend_debug:latest
    depends_on:
      - db
      - redis
      - php_backend
    volumes:
      - .:/var/www
  redis:
    image: redis:4.0.6
    ports:
      - "6379:6379"
    volumes:
      - .:/var/www
    command: ["redis-server", "/var/www/docker/redis/config/redis.conf"]
#  varnish:
#    build: docker/varnish

#    command: ["/usr/local/bin/start_varnish.sh"]
#    depends_on:
#      - web_server
#    environment:
#      CACHE_SIZE: 128m
#    ports:
#      - "80:80"
#    volumes:
#      - ./config/localdev/varnish:/etc/varnish
#      - ./:/var/app
  nginx:
    build: docker/nginx
    # image: example_web_server:latest
    depends_on:
      - db
      - redis
      - php_backend
      - php_backend_debug
    volumes:
      - .:/var/www
    ports:
      - "80:80"
      - "8000:8000"
      - "8001:8001"
#      dns_search:
#        - dc1.example.com
#        - dc2.example.com
#    networks:
#      default:
#        aliases:
#          - local.app.basereality.com


# https://rskuipers.com/entry/file-permissions-with-docker-on-linux
# fpm:
    # For Linux users only (UID of your user)
 #   user: "1000"